[package]
name = "twilight_commands_derive"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
darling = "0.21.3"
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = "2.0.111"
thiserror = "2.0.17"

[lib]
proc-macro = true
